### ISSUE TITLE
Duda en función

### ISSUE THREAD

**Issue by HugoAndres** [norman-ipn/ecuaciones-lineales#10]
Oye compa, exactamente ¿qué hace tu función? 
No me queda claro tu código. :(

**Comment by DavidISE** [comment]
Antes, solo restaba cada uno de los elementos de dos filas de la matriz, el primer elemento de la fila j menos el primer elemento de la fila i, y así se seguía con todos.
Pero se modificó, ahora multiplica toda la fila i por el primer elemento diferente de 0 de la fila j, guarda todos los resultados en un arreglo temporal t[ ], y después resta todos los elementos de la fila j con los elementos del arreglo t.
¿Ya te quedó claro? >:(
