### ISSUE TITLE
Modifiqué funcion_pedir_valores.c

### ISSUE THREAD

**Issue by DavidISE** [norman-ipn/ecuaciones-lineales#11]
Modifiqué su función compañeros, como declaraban la matriz dentro, no hacia ningun cambio a esta. Al cambiar su tipo a void, el cambio se conserva.

**Comment by sabrinapens** [comment]
Gracias. 
Encontraste agún otro error en el código por parte nuestra? 
Para modificarlo lo antes posible

**Comment by DavidISE** [comment]
No, solo fue ese cambio.
Gracias por responder :)
